---

- name: Install MySQL Server
  apt:
    name: mysql-server
    state: present
  become: yes
  become_method: sudo

- name: Install MySQL Client
  apt:
    name: mysql-client
    state: present
  become: yes
  become_method: sudo
  when: mysql.install_client

- name: Install MySQL Driver
  apt:
    name: libmysqlclient-dev
    state: present
  become: yes
  become_method: sudo
  when: mysql.install_driver
